controllers_admin:
  resource: ../../src/Controller/Admin
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_front:
  resource: ../../src/Controller/Front
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_robots_txt:
  resource: ../../src/Controller/Front/RobotsTxtController.php
  type: annotation
  format: txt
  requirements:
    _format: txt

kernel:
  resource: ../../src/Kernel.php
  type: annotation
